# Generated by Django 4.1.11 on 2023-09-19 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.FloatField(null=True)),
                ('future_value', models.FloatField(default=0)),
                ('descripition', models.TextField(max_length=300, null=True)),
                ('type', models.CharField(choices=[('CC', 'Conta Corrente'), ('DI', 'Dinheiro'), ('CA', 'Cartao'), ('IN', 'Investimento')], max_length=2)),
                ('color', models.CharField(choices=[('R', 'Vermelho'), ('B', 'Azul'), ('P', 'Roxo'), ('O', 'Laranja')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('future_value', models.FloatField()),
                ('extract_damege', models.FloatField()),
                ('extract_profit', models.FloatField()),
                ('teste', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('type', models.CharField(choices=[('P', 'Profit'), ('D', 'Damage')], max_length=1)),
                ('date', models.DateField()),
                ('descripition', models.TextField(max_length=300)),
                ('pay', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
    ]
