# Generated by Django 4.1.11 on 2023-09-28 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.FloatField(null=True)),
                ('extract_value', models.FloatField(default=0)),
                ('future_extract_value', models.FloatField(default=0)),
                ('descripition', models.TextField(blank=True, max_length=300)),
                ('type', models.CharField(choices=[('CC', 'Conta Corrente'), ('DI', 'Dinheiro'), ('CA', 'Cartao'), ('IN', 'Investimento')], max_length=2)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('type', models.CharField(choices=[('P', 'Profit'), ('D', 'Damage')], max_length=1)),
                ('date', models.DateField()),
                ('descripition', models.TextField(blank=True, max_length=300)),
                ('pay', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
