# Generated by Django 4.1.11 on 2023-09-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Money',
        ),
        migrations.RemoveField(
            model_name='account',
            name='future_value',
        ),
        migrations.AlterField(
            model_name='account',
            name='descripition',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='extract',
            name='descripition',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
