# Generated by Django 4.1.11 on 2023-09-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_money_remove_account_future_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='color',
        ),
        migrations.AddField(
            model_name='account',
            name='extract_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='future_extract_value',
            field=models.FloatField(null=True),
        ),
    ]
