# Generated by Django 4.1.11 on 2023-09-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_account_color_account_extract_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='extract_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='future_extract_value',
            field=models.FloatField(default=0),
        ),
    ]
