# Generated by Django 4.2.4 on 2023-08-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_money_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='future_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='money',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
