# Generated by Django 4.2.4 on 2023-08-27 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_money_future_value_money_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('CC', 'Conta Corrente'), ('DI', 'Dinheiro'), ('CA', 'Cartao'), ('IN', 'Investimento')], max_length=2),
        ),
        migrations.AlterField(
            model_name='extract',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account'),
        ),
    ]
