# Generated by Django 4.2.4 on 2023-08-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_account_type_alter_extract_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='extract_damege',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='money',
            name='extract_profit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
